ShortenURL/Models/Url.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ShortenURL.Models
{
    public class Url
    {
        [Required]
        [JsonProperty("longUrl")]
        public string LongURL { get; set; }

        [JsonProperty("shortenUrl")]
        public string ShortenURL { get; set; }

        [JsonIgnore]
        public string CustomAlias { get; set; }
    }
}

ShortenURL/Controllers/UrlController.cs
using Negocio;
using ShortenURL.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Threading.Tasks;
using Entities;

namespace ShortenURL.Controllers
{
    public class UrlController : Controller
    {
        private IRepositorioShorten _urlRepositorio;

        [HttpGet]
        public ActionResult Index()
        {
            Url url = new Url();
            return View();
        }

        public UrlController(IRepositorioShorten urlRepositorio)
        {
            this._urlRepositorio = urlRepositorio;
        }

        public async Task<ActionResult> Index(Url url)
        {
            if (ModelState.IsValid)
            {
                ShortenUrl shortenUrl = await this._urlRepositorio.ShortenUrl(url.LongURL, Request.UserHostAddress, url.CustomAlias);
                url.ShortenURL = string.Format("{0}://{1}{2}{3}", Request.Url.Scheme, Request.Url.Authority, Url.Content("~"), shortenUrl.Alias);
            }
            return View(url);
        }

        public async Task<ActionResult> Click(string segment)
        {
            string referer = Request.UrlReferrer != null ? Request.UrlReferrer.ToString() : string.Empty;
            Estatistica estatistica = await this._urlRepositorio.Estatisticas(segment, referer, Request.UserHostAddress);
            return this.RedirectPermanent(estatistica.ShortenUrl.LongUrl);
        }
    }
}

ShortenURL/Views/Shared/Error400.cshtml
@{
    ViewBag.Title = "Error";
}
<h2>Error</h2>

<p>Ocorreu um erro inesperado.</p>

ShortenURL/Views/Shared/Error404.cshtml
@{
    ViewBag.Title = "Not Found";
}

<h2>Not Found</h2>

<p>O recurso que você solicitou não foi encontrado.</p>

ShortenURL/Views/Shared/Error409.cshtml
@{
    ViewBag.Title = "Conflict";
}

<h2>Conflict</h2>

<p>O nome que você escolheu já existe.</p>

ShortenURL/Views/Shared/Error500.cshtml
@{
    ViewBag.Title = "Error";
}

<h2>Error</h2>

<p>Ocorreu um Erro inesperado.</p>

ShortenURL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Shortnr.net</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("ShortenUrl", "Url", "Index", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @*<li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("About", "About", "Home")</li>
                        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Shortnr.net</p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

ShortenURL/Views/Url/Index.cshtml
@model ShortenURL.Models.Url
@{
    ViewBag.Title = "URL shortener";
}

<h2>Shorten a URL</h2>

@Html.ValidationSummary()

@using (Html.BeginForm())
{
    <div class="form-group">
        @Html.TextBoxFor(model => model.LongURL, new { placeholder = "URL que você deseja encurtar.", @class = "form-control" })
    </div>

    <div class="form-group">
        @Html.TextBoxFor(model => model.CustomAlias, new { placeholder = "Se você quiser, pode customizar a palavra da sua URL.", @class = "form-control" })
    </div>


    if (!string.IsNullOrEmpty(Model.ShortenURL))
    {
        <div>
            <h3><a href="@Model.ShortenURL" target="_blank">@Model.ShortenURL</a></h3>
        </div>      
    }
    
    <input type="submit" class="btn btn-primary" value="Shorten" />
}